language: php

php:
  - 5.6
  - 7.0
  - 7.1

before_script:
  - composer selfupdate --no-progress
  - travis_retry composer install --prefer-dist
  - Vendor/bin/parallel-lint Monolog/ Tests/ -e php,php3,php4,php5,phtml,phpt --exclude vendor --blame
  - mkdir Tests/tmp

script:
  - Vendor/bin/tester Tests/ -C

after_script:
  - Vendor/bin/phpcs --standard=ruleset.xml --extensions=php --encoding=utf-8 --tab-width=4 -sp Monolog/
  - Vendor/bin/phpcs --standard=ruleset.xml --extensions=php,phpt --encoding=utf-8 --tab-width=4 -sp Tests/Adeira --ignore=*/output/*,_temp/*,bootstrap.php

notifications:
  email: false
